# Generated by Django 4.2.7 on 2024-01-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_data',
        ),
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
    ]
